# Generated by Django 4.1.7 on 2023-03-10 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория клиентов (М Ж)',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='НАзвание коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50, verbose_name='количество на складе')),
            ],
            options={
                'verbose_name': 'Наличие на складе',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 1')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 2')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 3')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 4')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 5')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('vendor_code', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('price', models.FloatField(verbose_name='цена')),
                ('colors', models.TextField(verbose_name='цвет')),
                ('size', models.TextField(verbose_name='размер')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('compound', models.TextField(verbose_name='Состав и уход')),
                ('size_on_model', models.TextField(verbose_name='Размер модели\\размер на модели')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.collection', verbose_name='Коллекция')),
                ('stock_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.stock', verbose_name='Наличие на складе')),
            ],
            options={
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='ClothingCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название раздела категории одежды')),
                ('client_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.clientcategory')),
            ],
            options={
                'verbose_name': 'Раздел категории одежды',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория одежды')),
                ('client_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.clothingcategories')),
            ],
            options={
                'verbose_name': 'Категория одежды',
            },
        ),
    ]
